# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleImport', '0002_auto_20170111_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='registered_domain',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
